### ISSUE TITLE
Hi xD

### ISSUE THREAD

**Issue by mccoderpy** [Luxa-Gaming/Discord-Bot-Cogs-Template#1]
**Never do shit in on_ready**
like change your presence or anything like that because anything could happen in on_ready like disconnecting, etc...

**Comment by mccoderpy** [comment]
> ```py
> async def on_ready():
>     print(f"Eingelogt als {bot.user}")
>     bot.loop.create_task(status_task())
> ```

**Comment by Luxa-Gaming** [comment]
Wird gemacht Chef!

**Comment by mccoderpy** [comment]
die musst du dann natürlich definieren (mit einem sleep)

**Comment by Luxa-Gaming** [comment]
> 
> 
> die musst du dann natürlich definieren (mit einem sleep)

Ich weiß, habe es in den anderen Projekten meistens auch so. Nur war das hier gerade einfacher. ^^

**Comment by mccoderpy** [comment]
```py
async def status_task():
    await bot.change_presence(activity=discord.Activity(type=discord.ActivityType.watching, name=f"{bot.users} users"), status=discord.Status.idle)
    await asyncio.sleep(100)
```

**Comment by Luxa-Gaming** [comment]
Done!

**Comment by mccoderpy** [comment]
Nice
boa ich bekomme dauernd E-Mails
